--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: bgst; Type: SCHEMA; Schema: -; Owner: ethanenger_25
--

CREATE SCHEMA bgst;


ALTER SCHEMA bgst OWNER TO ethanenger_25;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bgst_user; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.bgst_user (
    id integer NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    imageurl text,
    friendcode text
);


ALTER TABLE bgst.bgst_user OWNER TO ethanenger_25;

--
-- Name: bgst_user_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.bgst_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.bgst_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: board_game; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.board_game (
    id integer NOT NULL,
    title text NOT NULL,
    image_url text,
    max_players integer,
    min_players integer,
    estimated_play_time_minutes integer,
    date_published timestamp with time zone
);


ALTER TABLE bgst.board_game OWNER TO ethanenger_25;

--
-- Name: board_game_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.board_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.board_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.collection (
    id integer NOT NULL,
    bgst_user_id integer,
    board_game_id integer,
    date_added timestamp with time zone
);


ALTER TABLE bgst.collection OWNER TO ethanenger_25;

--
-- Name: collection_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friend; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.friend (
    id integer NOT NULL,
    bgst_user_1_id integer,
    bgst_user_2_id integer,
    date_accepted timestamp with time zone
);


ALTER TABLE bgst.friend OWNER TO ethanenger_25;

--
-- Name: friend_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.friend ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.friend_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friend_request; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.friend_request (
    id integer NOT NULL,
    bgst_user_1_id integer,
    bgst_user_2_id integer,
    date_sent timestamp with time zone
);


ALTER TABLE bgst.friend_request OWNER TO ethanenger_25;

--
-- Name: friend_request_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.friend_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.friend_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: played_game; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.played_game (
    id integer NOT NULL,
    board_game_id integer,
    date_played timestamp with time zone
);


ALTER TABLE bgst.played_game OWNER TO ethanenger_25;

--
-- Name: played_game_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.played_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.played_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_played_game; Type: TABLE; Schema: bgst; Owner: ethanenger_25
--

CREATE TABLE bgst.user_played_game (
    id integer NOT NULL,
    played_game_id integer,
    bgst_user_id integer,
    points integer,
    end_rand integer
);


ALTER TABLE bgst.user_played_game OWNER TO ethanenger_25;

--
-- Name: user_played_game_id_seq; Type: SEQUENCE; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE bgst.user_played_game ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bgst.user_played_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bgst_user; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.bgst_user (id, username, email, imageurl, friendcode) FROM stdin;
\.


--
-- Data for Name: board_game; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.board_game (id, title, image_url, max_players, min_players, estimated_play_time_minutes, date_published) FROM stdin;
\.


--
-- Data for Name: collection; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.collection (id, bgst_user_id, board_game_id, date_added) FROM stdin;
\.


--
-- Data for Name: friend; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.friend (id, bgst_user_1_id, bgst_user_2_id, date_accepted) FROM stdin;
\.


--
-- Data for Name: friend_request; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.friend_request (id, bgst_user_1_id, bgst_user_2_id, date_sent) FROM stdin;
\.


--
-- Data for Name: played_game; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.played_game (id, board_game_id, date_played) FROM stdin;
\.


--
-- Data for Name: user_played_game; Type: TABLE DATA; Schema: bgst; Owner: ethanenger_25
--

COPY bgst.user_played_game (id, played_game_id, bgst_user_id, points, end_rand) FROM stdin;
\.


--
-- Name: bgst_user_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.bgst_user_id_seq', 1, false);


--
-- Name: board_game_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.board_game_id_seq', 1, false);


--
-- Name: collection_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.collection_id_seq', 1, false);


--
-- Name: friend_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.friend_id_seq', 1, false);


--
-- Name: friend_request_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.friend_request_id_seq', 1, false);


--
-- Name: played_game_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.played_game_id_seq', 1, false);


--
-- Name: user_played_game_id_seq; Type: SEQUENCE SET; Schema: bgst; Owner: ethanenger_25
--

SELECT pg_catalog.setval('bgst.user_played_game_id_seq', 1, false);


--
-- Name: bgst_user bgst_user_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.bgst_user
    ADD CONSTRAINT bgst_user_pkey PRIMARY KEY (id);


--
-- Name: board_game board_game_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.board_game
    ADD CONSTRAINT board_game_pkey PRIMARY KEY (id);


--
-- Name: collection collection_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.collection
    ADD CONSTRAINT collection_pkey PRIMARY KEY (id);


--
-- Name: friend friend_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend
    ADD CONSTRAINT friend_pkey PRIMARY KEY (id);


--
-- Name: friend_request friend_request_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend_request
    ADD CONSTRAINT friend_request_pkey PRIMARY KEY (id);


--
-- Name: played_game played_game_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.played_game
    ADD CONSTRAINT played_game_pkey PRIMARY KEY (id);


--
-- Name: user_played_game user_played_game_pkey; Type: CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.user_played_game
    ADD CONSTRAINT user_played_game_pkey PRIMARY KEY (id);


--
-- Name: collection collection_bgst_user_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.collection
    ADD CONSTRAINT collection_bgst_user_id_fkey FOREIGN KEY (bgst_user_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: collection collection_board_game_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.collection
    ADD CONSTRAINT collection_board_game_id_fkey FOREIGN KEY (board_game_id) REFERENCES bgst.board_game(id) ON DELETE CASCADE;


--
-- Name: friend friend_bgst_user_1_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend
    ADD CONSTRAINT friend_bgst_user_1_id_fkey FOREIGN KEY (bgst_user_1_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: friend friend_bgst_user_2_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend
    ADD CONSTRAINT friend_bgst_user_2_id_fkey FOREIGN KEY (bgst_user_2_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: friend_request friend_request_bgst_user_1_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend_request
    ADD CONSTRAINT friend_request_bgst_user_1_id_fkey FOREIGN KEY (bgst_user_1_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: friend_request friend_request_bgst_user_2_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.friend_request
    ADD CONSTRAINT friend_request_bgst_user_2_id_fkey FOREIGN KEY (bgst_user_2_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: played_game played_game_board_game_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.played_game
    ADD CONSTRAINT played_game_board_game_id_fkey FOREIGN KEY (board_game_id) REFERENCES bgst.board_game(id) ON DELETE CASCADE;


--
-- Name: user_played_game user_played_game_bgst_user_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.user_played_game
    ADD CONSTRAINT user_played_game_bgst_user_id_fkey FOREIGN KEY (bgst_user_id) REFERENCES bgst.bgst_user(id) ON DELETE CASCADE;


--
-- Name: user_played_game user_played_game_played_game_id_fkey; Type: FK CONSTRAINT; Schema: bgst; Owner: ethanenger_25
--

ALTER TABLE ONLY bgst.user_played_game
    ADD CONSTRAINT user_played_game_played_game_id_fkey FOREIGN KEY (played_game_id) REFERENCES bgst.played_game(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

