# name: Build and Deploy Docker Images

# on:
#   push:
#     branches:
#       - main  # Change this to your main branch name

# jobs:
#   build:
#     runs-on: board-game-runner

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repository secrets
#           password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repository secrets

#       - name: Build and push server image
#         run: | 
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/board-game-stat-tracker:${{ github.run_number}} \
#           -t ${{ secrets.DOCKER_USERNAME }}/board-game-stat-tracker:latest .
#           docker push ${{ secrets.DOCKER_USERNAME }}/board-game-stat-tracker --all-tags

#       - name: Reapply Kube files
#         run: |
#           export GITHUB_RUN_ID=${{github.run_number}}

#           for file in ./kubernetes/*; do 
#             cat $file | envsubst | /home/ethane/.nix-profile/bin/kubectl apply -f -
#           done